version: '2'
services:
  test_volume:
    image: ubuntu:14.04
    volumes:
      - ./shared:/data:ro
  result_volume:
      image: ubuntu:14.04
      volumes:
        - ./results:/results
  nginx:
    build: ./nginx
    ports:
     - "8081:80"
    volumes_from:
     - test_volume
  nginx_http2:
        build: ./nginx_http2
        ports:
         - "8453:443"
        volumes_from:
         - test_volume
  nginx_varnish:
    build: ./nginx_varnish
    ports:
      - "8121:6081"
    volumes_from:
      - test_volume
  httpd:
    build: ./httpd
    ports:
     - "8091:80"
    volumes_from:
     - test_volume
  gwan:
      build: ./gwan
      ports:
       - "8101:80"
      volumes_from:
       - test_volume
  litespeed:
      build: ./litespeed
      ports:
        - "8111:80"
      volumes_from:
       - test_volume
  ab:
    build: ./ab
    environment:
      - NUMBER_OF_USERS=${NUMBER_OF_USERS}
      - REQUESTS_COUNT=${REQUESTS_COUNT}
    volumes_from:
     - test_volume
     - result_volume

