version: '2'
services:
  test_volume:
    image: ubuntu:14.04
    volumes:
      - ./shared:/data:ro
  nginx:
    build: ./nginx
    ports:
     - "8081:80"
    volumes_from:
     - test_volume
  httpd:
    build: ./httpd
    ports:
     - "8091:80"
    volumes_from:
     - test_volume

